#!/usr/bin/env python

"""
This script will add a random emoji to the beginning of your commit message.

To use this script, copy it to your .git/hooks/ directory and rename it to
prepare-commit-msg. Make sure it is executable.

This script need emoji package, you can install it by "pip install emoji".

This script created by Nima Mashhadi, you can find him on github:
https://github.com/n25a
"""

import sys
import emoji
import random


commit_msg_filepath = sys.argv[1]


emoji_list = []
for e in list(emoji.EMOJI_DATA.keys()):
    emoji_list.append(
        e[0]
        if len(e) > 1
        else e
    )

emoji_list = list(set(emoji_list))

with open(commit_msg_filepath, 'r+') as f:
    commit_msg = f.read()
    if not emoji.is_emoji(commit_msg):
        index = random.randint(0, len(emoji_list) - 1)
        f.seek(0, 0)
        prefix_emoji = emoji_list[index]
        new_commit_msg = '%s %s' % (prefix_emoji, commit_msg)
        f.write(new_commit_msg)
