version: '3.9'

services:
  db:
    image: mariadb:10.4.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root-secure-password"
      MYSQL_USER: "mobser_app"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "mobser"
    volumes:
      - db-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
  db-data:
    driver: local
